"""empty message

Revision ID: 538264df91d2
Revises: None
Create Date: 2014-09-23 16:55:41.296855

"""

# revision identifiers, used by Alembic.
revision = '538264df91d2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('company', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'company')
    ### end Alembic commands ###
